### PR TITLE
Scheduler_v1.1

### PR DESCRIPTION
**Pull request by C-E-OOI**
There is a new attribute schedule with the tag d/ that takes in DD-MM-YYYY together with the person detail. At the moment, it must be included for the a person to be added to this addressbook and each person can only enter 1 schedule.

### CODE REVIEW

**Comment by NichPang1** [comment]
Naise

**Comment by OngJiaJian** [comment]
Dayumm

**Comment by keithtqs** [comment]
siksiksik

**Comment by C-E-OOI** [comment]
#33 Create schedule
#34 Format for schedule input in DD-MM-YYYY

**Pull request merged**
